# Generated by Django 5.1.4 on 2025-04-12 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=256)),
                ('label', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='call_report_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPhoneNumber', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('issue', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('weekday', models.CharField(max_length=1)),
                ('call_date', models.CharField(max_length=50)),
                ('status', models.CharField(default='0', max_length=1)),
                ('workerPhoneNumber', models.CharField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_report_table_profile_User', to=settings.AUTH_USER_MODEL)),
                ('workerName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_report_table_profile_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=11)),
                ('dutyTime', models.CharField(default='0', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
