# Generated by Django 5.1.4 on 2025-04-25 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='report_message_board_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('reportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reportId', to='common.call_report_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_record_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
