# Generated by Django 5.1.4 on 2025-04-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_report_message_board_record_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_message_board_record',
            old_name='reportId',
            new_name='report',
        ),
    ]
