# Generated by Django 5.1.4 on 2025-04-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_reportid_report_message_board_record_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_message_board_record',
            name='date',
            field=models.CharField(default='2025-4-28 1:10', max_length=50),
            preserve_default=False,
        ),
    ]
