# Generated by Django 5.2 on 2025-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_report_message_board_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='call_report_table',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='call_report_table',
            name='rating',
            field=models.CharField(default='5', max_length=1),
        ),
    ]
