# Generated by Django 5.1.4 on 2024-12-23 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_report_table',
            name='username',
        ),
        migrations.AddField(
            model_name='call_report_table',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='call_report_table_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
