# Generated by Django 5.2 on 2025-05-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_call_report_table_comment_call_report_table_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_report_table',
            name='rating',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
