# Generated by Django 5.2 on 2025-05-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_call_report_table_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='call_report_table',
            name='notes',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
