# Generated by Django 5.2 on 2025-05-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_call_report_table_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_report_table',
            name='notes',
        ),
    ]
