# Generated by Django 5.1.4 on 2024-12-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_call_report_table_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_report_table',
            name='allocationState',
        ),
        migrations.RemoveField(
            model_name='call_report_table',
            name='completeState',
        ),
        migrations.AddField(
            model_name='call_report_table',
            name='call_date',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call_report_table',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
